Repository brainstormforce/astra-sites, pull requests merged in 2021-07, with the labels that each got.

#309 Add dependbot alerts for composer, npm and github-actions
  .github/dependbot.yml
Labels: needs review

#307 ST-240 - fix: handled white labelled case for template button text
  inc/lib/ast-block-templates/classes/class-ast-block-templates.php
  inc/lib/ast-block-templates/dist/main.js
Labels: ready to merge

#316 Build: Release PR v2.6.15 release preparation
  README.md
  astra-sites.php
  inc/assets/js/dist/common.js
  inc/assets/js/dist/index.js
  inc/assets/js/dist/main.asset.php
  inc/classes/class-astra-sites-importer.php
  inc/classes/functions.php
  inc/json/astra-sites-tags.json
  inc/lib/ast-block-templates/classes/class-ast-block-templates.php
  languages/astra-sites.pot
  package.json
  readme.txt
Labels: Release PR checklist

#319 Build: Release PR Free Images by Pixabay not available on Elementor Editor
  README.md
  astra-sites.php
  inc/assets/css/images-rtl.css
  inc/assets/css/images.css
  inc/assets/js/common.js
  inc/assets/js/dist/main.asset.php
  inc/assets/js/dist/main.js
  inc/assets/js/src/index.js
  inc/assets/js/src/search.js
  inc/classes/class-astra-sites.php
  languages/astra-sites.pot
  package.json
  readme.txt
Labels: Release PR checklist, needs review

#321 use actions from 10up instead of using the forked actions
  .github/workflows/push-asset-readme-update.yml.yml
  .github/workflows/push-to-deploy.yml
Labels: needs review

#324 Build: Release PR Update preparation
  .github/workflows/ci.yml
  README.md
  astra-sites.php
  languages/astra-sites.pot
  package.json
  readme.txt
Labels: Release PR checklist

#323 Updated the landing page links according to the current page builder selection.
  assets/js/admin.js
  classes/class-astra-sites-admin.php
  inc/assets/js/admin-page.js
Labels: needs review

#331 Build: Release PR v2.6.18 Release
  .github/workflows/ci.yml
  .github/workflows/release-pr-template.yml
  .gitignore
  README.md
  assets/js/admin.js
  astra-sites.php
  classes/class-astra-sites-admin.php
  composer.json
  composer.lock
  inc/assets/css/images-rtl.css
  inc/assets/css/images.css
  inc/assets/images/pixabay-logo.png
  inc/assets/js/admin-page.js
  inc/assets/js/common.js
  inc/assets/js/dist/main.asset.php
  inc/classes/batch-import/class-astra-sites-batch-site-import.php
  inc/classes/class-astra-sites-page.php
  inc/classes/class-astra-sites.php
  inc/includes/admin-page.php
  inc/includes/image-templates.php
  inc/lib/ast-block-templates/dist/json/ast-block-templates-categories.json
  inc/lib/ast-block-templates/version.json
  inc/lib/bsf-quick-links/class-bsf-quick-links.php
  inc/lib/class-astra-sites-ast-block-templates.php
  inc/lib/gutenberg-templates/ast-block-templates.php
  inc/lib/gutenberg-templates/classes/class-ast-block-templates-image-importer.php
  inc/lib/gutenberg-templates/classes/class-ast-block-templates-sync-library-wp-cli.php
  inc/lib/gutenberg-templates/classes/class-ast-block-templates-sync-library.php
  inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
  inc/lib/gutenberg-templates/classes/functions.php
  inc/lib/gutenberg-templates/composer.json
  inc/lib/gutenberg-templates/dist/fonts/ast-block-templates.eot
  inc/lib/gutenberg-templates/dist/fonts/ast-block-templates.svg
  inc/lib/gutenberg-templates/dist/fonts/ast-block-templates.ttf
  inc/lib/gutenberg-templates/dist/fonts/ast-block-templates.woff
  inc/lib/gutenberg-templates/dist/index.html
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-block-requests.json
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-blocks-1.json
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-blocks-2.json
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-blocks-3.json
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-site-requests.json
  inc/lib/gutenberg-templates/dist/json/ast-block-templates-sites-1.json
  inc/lib/gutenberg-templates/dist/logo.svg
  inc/lib/gutenberg-templates/dist/main.js
  inc/lib/gutenberg-templates/dist/placeholder.png
  inc/lib/gutenberg-templates/dist/placeholder_200_200.png
  inc/lib/gutenberg-templates/dist/starter-template-logo.svg
  inc/lib/gutenberg-templates/dist/style.css
  inc/lib/gutenberg-templates/version.json
  languages/astra-sites.pot
  package-lock.json
  package.json
  readme.txt
Labels: Release PR checklist
